version: "2"
services:
  app:
    container_name: starwars-api
    build:
      context: ./
      dockerfile: ./settings/Dockerfile.dev
    volumes:
      -  ./:/starwars
    ports:
      - "3000:3000"
    links:
      - mongodb:mongo
      - redis
  mongodb:
    image: mongo:latest
    container_name: starwars-mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ~/mongo/db:/data/db
    ports:
      - 36087:36087
    expose:
      - 36087
    command: mongod --smallfiles --logpath=/dev/null --port 36087
  redis:
    image: redis:latest
    container_name: starwars-redis
    command: redis-server --port 9830
    ports:
      - "9830:9830"
    expose:
      - 9830
